"""The `avallon` command: one entry point for the site and its notes.

There is no standalone CLI here, only the handful of operations a note site
needs around itself: run it, point it at a notes repository, scaffold and
re-file pages, sync, export. Each subcommand delegates to the module that
already implements it, so this file stays a dispatcher and never becomes a
second implementation.

Subcommands parse their own arguments (they each own an argparse parser, or a
positional grammar), so everything after the subcommand name is handed over
untouched.
"""

from __future__ import annotations

import argparse
import os
import sys
from collections.abc import Sequence
from pathlib import Path

USAGE = """\
avallon <command> [options]

  version               print the installed version and where it reads from
  serve                 run the site
  init <path|url>       create or adopt a notes repository, and activate it
  repo [path]           print or switch the active repository
  language [en|fr]      print or switch the interface language
  new                   create a page
  add-file <path>       promote a file to a page of its own
  move                  re-file a page under another domain/type
  rename <page> <title> rename a page, keeping its links alive
  sync                  pull, commit, push
  export                export a page to .docx or .pdf
  add-domain <name>     extend the vocabulary
  add-type <name>       extend the vocabulary
  check                 verify every page sits under a declared pair
  check-links           verify every [[link]] resolves
  stamp                 fill the missing frontmatter dates
  setup                 write the environment file (address, token)
  install               install and start the systemd user unit
"""


def _is_loopback(host: str) -> bool:
    """Whether *host* can only be reached from this machine."""
    import ipaddress

    if host in ("localhost", ""):
        return True
    try:
        return ipaddress.ip_address(host.strip("[]")).is_loopback
    except ValueError:
        return False


def _serve(argv: Sequence[str]) -> int:
    """Run the ASGI server.

    Uvicorn rather than ``runserver``: the live-reload stream is a real SSE
    response, and the WSGI development server buffers it instead of streaming.
    """
    import uvicorn

    parser = argparse.ArgumentParser(prog="avallon serve")
    parser.add_argument("--host", default=os.environ.get("AVALLON_HOST", "127.0.0.1"))
    parser.add_argument(
        "--port", type=int, default=int(os.environ.get("AVALLON_PORT", "8000"))
    )
    parser.add_argument("--reload", action="store_true", help="reload on every change")
    args = parser.parse_args(argv)

    # The guard is a no-op without a token, which only holds on loopback. Any
    # other bind reaches other machines, so refuse rather than serve the notes
    # to whoever finds the port.
    if not _is_loopback(args.host) and not os.environ.get("AVALLON_TOKEN", "").strip():
        sys.exit(
            f"Refusing to serve on {args.host} without an access token.\n"
            "  AVALLON_TOKEN=$(openssl rand -hex 32) avallon serve --host "
            f"{args.host}\n"
            "  (or `avallon setup`, which generates one and writes it to the "
            "environment file)"
        )

    # Watch the package itself rather than the working directory: it holds the
    # templates and the stylesheet as well as the code, and it is the same
    # place whether avallon runs from a checkout or from site-packages.
    package_dir = str(Path(__file__).resolve().parent)
    uvicorn.run(
        "avallon.settings.asgi:application",
        host=args.host,
        port=args.port,
        reload=args.reload,
        reload_dirs=[package_dir] if args.reload else None,
        reload_includes=["*.html", "*.css"] if args.reload else None,
        # The live-reload stream never ends on its own, so a graceful shutdown
        # waits on a reader's open tab forever: editing a template would hang
        # the reloader instead of restarting it, and the port stays held by a
        # worker that no longer serves. Cut the wait short.
        timeout_graceful_shutdown=3,
    )
    return 0


def _setup(argv: Sequence[str]) -> int:
    """Write the environment file a deployment reads: address, port, token."""
    from avallon import deploy
    from avallon.notes import config

    parser = argparse.ArgumentParser(prog="avallon setup")
    parser.add_argument("--host", default="127.0.0.1", help="bind address")
    parser.add_argument("--port", type=int, default=8000, help="bind port")
    parser.add_argument(
        "--token", default="", help="access token (generated by default)"
    )
    parser.add_argument(
        "--content-dir", help="notes repository (default: the active one)"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite the existing file and rotate the token",
    )
    args = parser.parse_args(argv)

    env_path = deploy.env_file_path()
    # Rewriting silently would rotate the token, and every device that holds a
    # session would be logged out without anyone asking for it.
    if env_path.exists() and not args.force:
        sys.exit(
            f"An environment already exists: {env_path}\n"
            "  --force to overwrite it and rotate the token"
        )

    if args.content_dir:
        content_dir: Path | None = Path(args.content_dir).expanduser().resolve()
        if content_dir is not None and not content_dir.exists():
            sys.exit(f"Notes repository not found: {content_dir}")
    else:
        try:
            content_dir = config.resolve_content_dir()
        except config.NotConfigured:
            content_dir = None

    token = args.token or deploy.generate_token()
    path = deploy.write_env(
        env_path, deploy.render_env(args.host, args.port, token, content_dir)
    )
    print(f"Wrote {path} (mode 0600).")
    print(f"  notes : {content_dir if content_dir else '(none)'}")
    print(f"  bind  : {args.host}:{args.port}")
    print(f"  token : {token}")
    if content_dir is None:
        print("  ! no notes repository: run `avallon init <path|url>`")
    print("\nNext: `avallon serve` to try it, or `avallon install` for a")
    print("systemd service.")
    return 0


def _install(argv: Sequence[str]) -> int:
    """Install (and, by default, start) the systemd user unit."""
    from avallon import deploy

    parser = argparse.ArgumentParser(prog="avallon install")
    parser.add_argument(
        "--no-start",
        action="store_true",
        help="only write the unit, and print the systemctl commands",
    )
    args = parser.parse_args(argv)

    env_path = deploy.env_file_path()
    if not env_path.exists():
        sys.exit(f"No environment at {env_path}: run `avallon setup` first")

    unit = deploy.write_unit(env_path)
    print(f"Wrote {unit}.")

    if args.no_start:
        print("\nEnable it with:")
        print("  systemctl --user daemon-reload")
        print(f"  systemctl --user enable --now {deploy.UNIT_NAME}")
    elif not _start_service():
        return 1

    # Without lingering, a user unit stops at logout, which is exactly when a
    # server is expected to keep running.
    print(
        "\nTo keep it running after logout and across reboots:\n"
        "  loginctl enable-linger $USER"
    )
    return 0


def _start_service() -> bool:
    """Reload systemd and enable/start the unit; return whether it succeeded."""
    from avallon import deploy

    steps = (
        ["daemon-reload"],
        ["enable", "--now", deploy.UNIT_NAME],
    )
    for step in steps:
        result = deploy.systemctl(*step)
        if result.returncode != 0:
            print(
                f"avallon: `systemctl --user {' '.join(step)}` failed:",
                file=sys.stderr,
            )
            print(result.stderr.strip(), file=sys.stderr)
            print(
                "Run the systemctl commands by hand (see `install --no-start`).",
                file=sys.stderr,
            )
            return False
    print(f"Started {deploy.UNIT_NAME}.")
    print(f"  systemctl --user status {deploy.UNIT_NAME}")
    return True


def _language(argv: Sequence[str]) -> int:
    """Print or switch the interface language."""
    from avallon.notes import config

    if not argv:
        active = config.resolve_language()
        source = (
            "env"
            if os.environ.get(config.LANGUAGE_ENV)
            else ("config" if config.read_language() else "default")
        )
        print(f"language : {active}  ({source})")
        print(f"available: {', '.join(config.LANGUAGES)}")
        return 0

    choice = argv[0].strip().lower()
    if choice not in config.LANGUAGES:
        sys.exit(
            f"unknown language: {choice}  (available: {', '.join(config.LANGUAGES)})"
        )
    path = config.write_language(choice)
    print(f"Interface language: {choice}")
    print(f"  wrote {path}")
    print("\nRestart the server for it to take effect.")
    return 0


def _version() -> int:
    """Print what is installed, and what it is looking at.

    A running site that behaves like an older one is the hardest thing to
    diagnose from the outside, and the answer is almost always that the service
    was not restarted after an upgrade, or that it reads a different tree. Both
    are one line each here.
    """
    from importlib.metadata import PackageNotFoundError, version

    from avallon.notes import config

    try:
        installed = version("avallon")
    except PackageNotFoundError:
        installed = "(not installed as a package)"
    print(f"avallon {installed}")
    print(f"  module : {Path(__file__).resolve().parent}")
    try:
        print(f"  notes  : {config.resolve_content_dir()}  ({config.content_source()})")
    except config.NotConfigured as exc:
        print(f"  notes  : {exc}")
    print(f"  lang   : {config.resolve_language()}")
    return 0


def _django(command: list[str]) -> int:
    """Run a Django management command in-process."""
    from django.core.management import execute_from_command_line

    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "avallon.settings.settings")
    execute_from_command_line(["avallon", *command])
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    """Dispatch to the subcommand named by the first argument."""
    from avallon.notes.config import NotConfigured

    try:
        return _dispatch(list(sys.argv[1:] if argv is None else argv))
    except NotConfigured as exc:
        # Reaching the notes without having chosen them is an ordinary mistake,
        # not a crash: say what to run, not where the exception came from.
        sys.exit(str(exc))


def _dispatch(args: list[str]) -> int:
    """Route *args* to the module implementing the subcommand."""
    if not args or args[0] in ("-h", "--help", "help"):
        print(USAGE, end="")
        return 0

    command, rest = args[0], args[1:]
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "avallon.settings.settings")

    if command in ("version", "--version", "-V"):
        return _version()

    if command == "serve":
        return _serve(rest)

    if command in ("init", "repo"):
        from avallon.notes import repo

        if command == "init":
            if not rest:
                sys.exit("usage: avallon init <path|url>")
            return repo.main(["init", *rest])
        return repo.main(["set", *rest] if rest else ["where"])

    if command == "language":
        return _language(rest)

    if command == "new":
        from avallon.notes import scaffold

        sys.argv = ["avallon new", *rest]
        return scaffold.main()

    if command == "add-file":
        from avallon.notes import add_file

        sys.argv = ["avallon add-file", *rest]
        return add_file.main()

    if command == "move":
        from avallon.notes import move

        sys.argv = ["avallon move", *rest]
        return move.main()

    if command == "rename":
        from avallon.notes import rename

        sys.argv = ["avallon rename", *rest]
        return rename.main()

    if command == "sync":
        from avallon.notes import sync

        return sync.main(rest)

    if command == "stamp":
        from avallon.notes import stamp

        sys.argv = ["avallon stamp", *rest]
        return stamp.main()

    if command == "check-links":
        from avallon.notes import links

        return links.main(list(rest))

    if command in ("add-domain", "add-type", "check"):
        from avallon.notes import taxonomy

        return taxonomy.main([command, *rest])

    if command == "setup":
        return _setup(rest)

    if command == "install":
        return _install(rest)

    if command == "export":
        return _django(["export", *rest])

    print(f"unknown command: {command}\n", file=sys.stderr)
    print(USAGE, end="", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
