"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Root of the Markdown content tree (<domaine>/<type>/<slug>/index.md), plus
# taxonomy.toml. Its location is user-configurable and lives *outside* this repo
# by default (see scripts/content_config.py): env KW_CONTENT_DIR, else the
# ~/.config/kevin-website/config.toml pointer, else the in-repo content/ (dev).
_SCRIPTS = BASE_DIR.parent / "scripts"
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))
from content_config import resolve_content_dir  # noqa: E402

CONTENT_DIR = resolve_content_dir()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-REDACTED"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "markdownify.apps.MarkdownifyConfig",
    "pages",
]

# django-markdownify configuration, tuned for scientific writing.
#
# BLEACH is turned OFF: the Markdown is authored by the site owner (trusted
# content), not submitted by visitors. Disabling the sanitizer lets the rich
# HTML produced by the extensions below (syntax-highlight spans, MathJax
# wrappers, admonition divs) pass through without whitelisting dozens of
# tags/classes. /!\ If this site ever renders user-submitted Markdown, turn
# BLEACH back on and whitelist tags/attrs explicitly.
MARKDOWNIFY = {
    "default": {
        "BLEACH": False,
        "MARKDOWN_EXTENSIONS": [
            # Core python-markdown extensions
            "markdown.extensions.tables",      # tables
            "markdown.extensions.footnotes",   # [^1] footnotes
            "markdown.extensions.attr_list",   # {: .class #id } on elements
            "markdown.extensions.def_list",    # definition lists
            "markdown.extensions.abbr",        # abbreviations
            "markdown.extensions.md_in_html",  # markdown inside raw HTML blocks
            "markdown.extensions.sane_lists",  # predictable list numbering
            "markdown.extensions.toc",         # heading anchors / [TOC]
            "markdown.extensions.admonition",  # !!! note / warning boxes
            # pymdown-extensions
            "pymdownx.superfences",            # ```lang fenced code boxes
            "pymdownx.highlight",              # Pygments syntax highlighting
            "pymdownx.inlinehilite",           # `#!python inline` code
            "pymdownx.arithmatex",             # LaTeX math -> MathJax
            "pymdownx.tasklist",               # - [ ] task lists
            "pymdownx.caret",                  # ^superscript^ and <ins>
            "pymdownx.tilde",                  # ~subscript~ and ~~strike~~
            "pymdownx.smartsymbols",           # (c) (tm) --> etc.
            # Local extension: [[slug]] cross-references between pages.
            "pages.mdx.wikilinks",
        ],
        "MARKDOWN_EXTENSION_CONFIGS": {
            # generic=True emits \(...\) / \[...\] spans for MathJax to render
            "pymdownx.arithmatex": {"generic": True},
            "pymdownx.highlight": {"css_class": "highlight", "guess_lang": False},
            "pymdownx.tasklist": {"custom_checkbox": True},
            "toc": {"permalink": "#"},
        },
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "pages.context_processors.navigation",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
