#!/usr/bin/env python3
"""Download the site's webfonts and regenerate the self-hosted stylesheet.

Fonts are served from our own static files (no request to a third party at page
load), so adding or changing a family means fetching new .woff2 files and
rewriting the @font-face rules. This script does both from a single FAMILIES
table, keeping the two the site actually needs (latin, latin-ext) and dropping
the cyrillic/greek/vietnamese subsets Google also serves.

Run from the repo root; it rewrites the font directory and the stylesheet:

    python scripts/gen_fonts.py
"""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

CSS_API = "https://fonts.googleapis.com/css2"
# Google serves woff2 only to browsers that advertise support; a bare urllib
# user-agent gets the legacy truetype payload instead.
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/120.0.0.0 Safari/537.36"
)

FONT_DIR = Path("src/avallon/web/static/avallon/fonts")
CSS_PATH = Path("src/avallon/web/static/avallon/css/fonts.css")

# (family, css2 query, comment). Order drives the output order. All three are
# variable fonts, so weights are asked for as a *range*: Google then serves one
# file covering 400-700 instead of the same bytes once per named weight.
FAMILIES = [
    (
        "Source Serif 4",
        "Source+Serif+4:ital,opsz,wght@0,8..60,400..700;1,8..60,400..700",
        "prose",
    ),
    ("Roboto", "Roboto:ital,wght@0,400..700;1,400..700", "UI chrome"),
    ("Roboto Mono", "Roboto+Mono:wght@400..700", "code"),
]

# Subsets to keep, in the order Google labels them with a /* comment */.
KEEP = {"latin", "latin-ext"}

_BLOCK = re.compile(
    r"/\* (?P<subset>[\w-]+) \*/\s*(?P<rule>@font-face \{.*?\})", re.DOTALL
)
_PROP = re.compile(r"(?P<key>[\w-]+):\s*(?P<val>[^;]+);")


def _fetch(url: str) -> bytes:
    """Return the body of *url*, posing as a modern browser."""
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:  # noqa: S310 (fixed host)
        return resp.read()


def _slug(family: str) -> str:
    """Turn a family name into a filename-safe stem ("Roboto Mono" -> roboto-mono)."""
    return re.sub(r"[^a-z0-9]+", "-", family.lower()).strip("-")


def _blocks(query: str) -> list[dict[str, str]]:
    """Fetch one family's css2 output and return its kept @font-face rules."""
    css = _fetch(f"{CSS_API}?family={query}&display=swap").decode("utf-8")
    out: list[dict[str, str]] = []
    for m in _BLOCK.finditer(css):
        if m["subset"] not in KEEP:
            continue
        props = {p["key"]: p["val"].strip() for p in _PROP.finditer(m["rule"])}
        props["subset"] = m["subset"]
        out.append(props)
    return out


def main() -> int:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in FONT_DIR.glob("*.woff2"):
        stale.unlink()

    lines = [
        "/* Self-hosted webfonts (latin, latin-ext). Generated by",
        "   scripts/gen_fonts.py; edit that script, not this file. */",
    ]
    for family, query, role in FAMILIES:
        stem = _slug(family)
        for props in _blocks(query):
            weight = props["font-weight"]
            style = props["font-style"]
            subset = props["subset"]
            name = f"{stem}-{weight.replace(' ', '-')}-{style}-{subset}.woff2"
            url = re.search(r"url\((.*?)\)", props["src"])
            assert url is not None, f"no url in src for {family}"
            (FONT_DIR / name).write_bytes(_fetch(url[1]))

            lines += [
                "",
                f"/* {family} {weight} {style} ({role}), {subset} */",
                "@font-face {",
                f"  font-family: '{family}';",
                f"  font-style: {style};",
                f"  font-weight: {weight};",
                "  font-display: swap;",
                f"  src: url(../fonts/{name}) format('woff2');",
                f"  unicode-range: {props['unicode-range']};",
                "}",
            ]
            print(f"  {name}")

    CSS_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {CSS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
