#!/usr/bin/env python3
"""Generate a theme-aware Pygments stylesheet.

The site flips light/dark with CSS `color-scheme` (no theme class), so syntax
colors must adapt through `light-dark()` too. This merges a light style and a
dark style token by token: every `color` / `background` becomes
`light-dark(<light>, <dark>)`, while weight/style properties are theme-neutral
and copied as-is. Run it to regenerate the checked-in stylesheet:

    python scripts/gen_pygments.py > src/pages/static/pages/css/pygments.css
"""

from __future__ import annotations

import re

from pygments.formatters import HtmlFormatter

LIGHT_STYLE = "friendly"
DARK_STYLE = "github-dark"

# Fallback foreground for a token one style colors and the other doesn't, so the
# `light-dark()` pair is always complete. They match the code box's plain text.
LIGHT_DEFAULT = "#1f2328"
DARK_DEFAULT = "#c9d1d9"

COLOR_PROPS = {"color"}
BG_PROPS = {"background", "background-color"}

_RULE = re.compile(r"([^{}]+)\{([^}]*)\}")


def _defs(style: str) -> dict[str, dict[str, str]]:
    """Parse HtmlFormatter's CSS into {selector: {property: value}}."""
    css = HtmlFormatter(style=style).get_style_defs(".highlight")
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.DOTALL)  # drop token labels
    rules: dict[str, dict[str, str]] = {}
    for sel, body in _RULE.findall(css):
        props: dict[str, str] = {}
        for decl in body.split(";"):
            key, sep, val = decl.partition(":")
            if sep:
                props[key.strip()] = val.strip()
        rules[sel.strip()] = props
    return rules


def _merge(sel: str, light: dict[str, str], dark: dict[str, str]) -> str:
    keys = list(dict.fromkeys([*light, *dark]))  # union, light order first
    out: list[str] = []
    for key in keys:
        lv, dv = light.get(key), dark.get(key)
        if key in COLOR_PROPS:
            out.append(
                f"color: light-dark({lv or LIGHT_DEFAULT}, {dv or DARK_DEFAULT})"
            )
        elif key in BG_PROPS:
            out.append(
                f"{key}: light-dark({lv or 'transparent'}, {dv or 'transparent'})"
            )
        else:
            out.append(f"{key}: {lv or dv}")
    return f"{sel} {{ {'; '.join(out)} }}"


def main() -> int:
    light = _defs(LIGHT_STYLE)
    dark = _defs(DARK_STYLE)
    order = list(light) + [s for s in dark if s not in light]

    print(
        f"/* Theme-aware Pygments styles (light={LIGHT_STYLE}, dark={DARK_STYLE}),\n"
        f"   merged into light-dark() pairs. Generated by scripts/gen_pygments.py;\n"
        f"   edit that script, not this file. */"
    )
    for sel in order:
        print(_merge(sel, light.get(sel, {}), dark.get(sel, {})))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
